env:
  global:
    - CONAN_RUN_TESTS: 1
    - CONAN_DOCKER_32_IMAGES: 1

linux: &linux
  os: linux
  dist: xenial
  language: python
  python: "3.7"
  services:
    - docker
osx: &osx
  os: osx
  language: generic
matrix:
  include:
    - <<: *linux
      env: CONAN_GCC_VERSIONS=9 CONAN_DOCKER_IMAGE=conanio/gcc9 DEPLOY_DOCS=TRUE

install:
  - chmod +x .travis/install.sh
  - ./.travis/install.sh

script:
  - chmod +x .travis/run.sh
  - ./.travis/run.sh
  - |
    # Prepare documentation for deployment
    if [ -n "$DEPLOY_DOCS" ]; then
      rm -rf gh-pages
      sudo -E docker run --name docker_deploy $CONAN_DOCKER_IMAGE /bin/sh -c "conan remote add conan-mpusz https://api.bintray.com/conan/mpusz/conan-mpusz"
      sudo -E docker exec docker_deploy /bin/sh -c "conan search -r conan-mpusz mp-units --raw | tail -n1 | xargs -I % conan install % -g deploy -s compiler.version=$CONAN_GCC_VERSIONS -s compiler.cppstd=20"
      sudo -E docker cp docker_deploy:/home/conan/mp-units/share/doc/units/sphinx gh-pages
    fi

before_deploy:

deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN # Set in travis-ci.org dashboard
  keep_history: true
  local_dir: gh-pages
  on:
    branch: master
